### ISSUE TITLE
Feature request: Control outcomes

### ISSUE THREAD

**Issue by SlimeDog** [I2000C/NewAmazingLuckyBlocks#7]
Please implement ability to control outcomes.
(This request has been separated from #2)

**Comment by SlimeDog** [comment]
- Enable or disable various outcomes. This should be cleanly done by modifying the probabilities.
- Add new outcomes. This would require a configuration structure that allows any object to be specified. For example, something like (YMMV):
```
outcomes:
 0:
    probability: 1.0
    object: 
      item: DIAMOND_SWORD
      count: 1
      enchantments:
      - FIREWORK (whatever else is required to define it)
  1:
    probability: 1.0
    object:
      item: EMERALD
      count: 32
    object:
      structure: villager tower (however that is defined, preferably as a WE structure)
  2:
    probability: 3.0
    object:
      item: STONE_PICKAXE
      count: 1
    object:
      item: STONE_AXE
      count: 1
    object:
      item: STONE_SPADE
      count: 1
...
  23:
    probability: 2.0
    object:
      entity: ZOMBIE
      count: 1
      age: ...
      helmet:
        item: IRON_HELMET
        enchantments: ...
      chestplate:
        item: IRON_CHESTPLATE
        enchantments: ...
      weapon:
        item: IRON_SWORD
        enchantments: ...
```
- Generated structures should never replace blocks with blast-resistance >= a configurable number, default 6000.
- Generated structures should never replace blocks in WG (or similar) protected regions.
- Probabilities do not have to sum to 100. The divisor is just the sum. :)

**Comment by I2000C** [comment]
Hi, I have just added the custom outcomes option to NALB. For the moment it only supports items. Different types of outcomes will eventually come. 

If you want to add custom outcomes:

1. Open the "custom_outcomes.yml" file that will generate the plugin
2. Change the 'Main-probability' option to the number that you want. Moreover, change the 'Main-probability' option in the "outcomes_probability.yml" file to other number. Depending on these numbers, it will occur a default outcome or a custom one.
3. In the "custom_outcomes.yml" file there are 2 examples of how custom-outcomes work. You can add as many outcomes as you want, also, you can edit the example outcomes.
4. The compulsory sections that you must add for each new outcome are:
     'outcome-name': The name of the outcome
     'probability': The probability of the outcome in the custom-outcomes list
     'rewards': The reward type (At the moment, it is only available the 'item' reward)
5. In the 'item' reward, you can add as many items as you need, each one with its material, amount, name, lore, enchantments and durability.
At least you have to add and fill the 'material' and the 'amount' fields. The rest are optional.

Test it when you can.
(Note that this version can contain bugs or errors, so make a backup of the previous config files)


[NewAmazingLuckyBlocks_custom-outcomes_test.zip](https://github.com/I2000C/NewAmazingLuckyBlocks/files/3197494/NewAmazingLuckyBlocks_custom-outcomes_test.zip)

**Comment by SlimeDog** [comment]
Thanks. I will test over the next few days.

**Comment by SlimeDog** [comment]
Spigot 1.13.2 final

Custom outcomes seem to work fine. Nice! Questions:
- Do the two Main-probability values need to sum to 100, or are they just compared in the probability calculation?
- The custom outcomes include LEGACY_WOOL with durability (ie, color) 5. New 1.13.2 materials seem to be recognized -- for example RED_WOOL -- if running on 1.13.2. I'm guessing that legacy nomenclature was used to support pre-1.13.2 versions?
- Are 1.14 materials recognized if running on 1.14.x (I did not try it)?
- Outcomes_probabilitiy ids are not sequential (skipped numbers). Do custom_outcomes ids need to be sequential? Do they need to start at 0?

Looking forward to the other reward types: **Entities** should be relatively straightforward; **Other** more difficult. :)

**Comment by I2000C** [comment]
- They are just compared in the probability calculation, so they don't have to sum to 100.
- You can use both "LEGACY_WOOL" and "_color_ _WOOL" materials if you are on >=1.13 minecraft version.
In <1.13 versions, you can only use the legacy materials without the "LEGACY_" prefix
- In 1.14 everything appears to work correctly
- There are two type of ids:
      - Outcome ids
      - Item ids in rewards field
Each one start at 0 and increases 1 for each new outcome/item following that structure.

I have thought about adding 5 different types of rewards inside each outcome:
- Items (This has been already added)
- Entities
- Commands
- Effects
- Structures

Besides, I would like to add a GUI so that outcomes can be created from an inventory menu.

**Comment by SlimeDog** [comment]
Thanks.
With **commands**, many things -- including item, entities, and effects -- will be possible. Even some structures will be possible. So please add **commands** first. :)

**Comment by I2000C** [comment]
ok

**Comment by I2000C** [comment]
[NewAmazingLuckyBlocks_custom-outcomes_test2.zip](https://github.com/I2000C/NewAmazingLuckyBlocks/files/3207204/NewAmazingLuckyBlocks_custom-outcomes_test2.zip)

I have just finished the command rewards and part of the GUI.
You can test the command rewards by following the next structure (Outcome 2):
![example3](https://user-images.githubusercontent.com/29607352/58172816-e7a98d80-7c99-11e9-8bbc-0def2275f7a1.png)
It's important that you don't include the '/' before each command.
The '%player%' parameter can be used to write the player's name in the command.

You can also combine items with commands.

If you want to test the GUI, use the "/alb menu" command and select the 'Create new outcome' option. Then, click in the 'name' item and write the outcome name in the chat.
Then, click in the 'probability' item and write the outcome probability in the chat.
Finally, click in the 'next' item.

Now, select the reward that you want to add and configure them (At the moment, only options 'Item Rewards' and 'Command Rewards' are available).
After you configure the first reward, in the next menu, you can select adding more rewards or save the previus one(s).

Test it when you can :)

**Comment by SlimeDog** [comment]
Thanks. I will test later today. No GUI for me. :)

**Comment by SlimeDog** [comment]
How does one run a Skript script?

**Comment by I2000C** [comment]
> How does one run a Skript script?

I have never run a Skript script.
Google must have the answer.

**Comment by SlimeDog** [comment]
In general (ie in-game) I just type the **_scriptName_**. In some plugins, that works. In ALB, it does not. Nor does **_skript:scriptName_**, which also works in-game.

**Comment by I2000C** [comment]
> In general (ie in-game) I just type the **_scriptName_**. In some plugins, that works. In ALB, it does not. Nor does **_skript:scriptName_**, which also works in-game.


Mmm... But, why do you want to use skript scripts with ALB?

**Comment by SlimeDog** [comment]
> Mmm... But, why do you want to use skript scripts with ALB?

In order to put some logic behind the selection and presentation of the reward. For example
- check the possible placement of a structure, before it is placed
- change a reward based on player attributes, groups, permissions, etc.
- _ad nauseam_

**Comment by I2000C** [comment]
> > Mmm... But, why do you want to use skript scripts with ALB?
> 
> In order to put some logic behind the selection and presentation of the reward. For example
> 
> * check the possible placement of a structure, before it is placed
> * change a reward based on player attributes, groups, permissions, etc.
> * _ad nauseam_

Now I understand you. However, how can I add this to ALB?

**Comment by SlimeDog** [comment]
There must be a way to execute Skripts as commands. Other plugins can do so.

**Comment by I2000C** [comment]
What plugins? Give me at least one example in order to know how it executes Skripts.
Then, I would try to add that function to ALB.

**EDIT:** Since skript scripts are commands, they can be executed from players or from console.
I believe the skript that you want to run with ALB needs to be executed from a player, no?
Command's rewards in ALB are executed only from the console, so this can be the problem.
Then I'll change this and I'll upload the plugin file.

**Comment by SlimeDog** [comment]
[DeluxeMenus](https://www.spigotmc.org/resources/deluxemenus.11734/) runs skripts. For example, the skript
```
command /set-home:
	permission: blackdog.sethome
	description: Create a home, where permitted.
	usage: /set-home
	trigger:
```
can be run by this DeluxeMenus configuration
```
items:
...
  'set-home':
    material: BED
    data: 14
    slot: 9
    priority: 1
    view_requirement:
      requirements:
        access_requirement:
          type: has permission
          permission: 'blackdog.sethome'
    display_name: '&a◎&lSet home'
    lore:
    - 'Put down roots'
    - 'in the current world'
    left_click_requirement:
      requirements:
        access_requirement:
          type: has permission
          permission: 'blackdog.sethome'
        access_requirement:
          type: has permission
          permission: 'multiverse.access.world'
    left_click_commands:
    - '[player] set-home'
    - '[close]'
    right_click_commands:
    - '[message] left-click please'
...
```
but DeluxeMenus is not open-source, so I don't know how he does it. Perhaps he'll share.

[CommandSigns](https://www.spigotmc.org/resources/command-signs.10512/) runs skripts. For example, the skript
```
command /equip-luckyblock <text=none>:
	description: give player luckyblocks
	usage: /equip-luckyblock player
	permission: command.equip
	trigger:
```
can be run by this CommandSigns configuration (a player right-clicks a sign to execute it)
```
{
  "id": 66,
  "name": "LuckyBlocks 2",
  "disabled": false,
  "activation_mode": "BOTH",
  "location": {
    "world": "world_luckyblock",
    "x": 3,
    "y": 9,
    "z": 0
  },
  "timer": {
    "duration": 0,
    "cancelled_on_move": false,
    "reset_on_move": false
  },
  "commands": [
    "/equip-luckyblock"
  ],
  "temporarily_granted_permissions": [
    "command.equip"
  ],
  "addons": {
    "ncs_economy": {
      "price": 0.0
    },
    "ncs_required_permissions": {
      "required_permissions": []
    },
    "ncs_cooldowns": {
      "is_global_once": false,
      "is_player_once": false,
      "global_cooldown": 0,
      "player_cooldown": 0
    }
  }
}
```
CommandSigns is open-source.

In neither case is there any indication that the command is a skript.

Skripts can be run either from the console or in-game (with appropriate permissions). For example, the skript
```
command /shutdown [<number=120>] [<text="We'll be right back!">]:
	description: Shutdown server with notice.
	usage: /shutdown [seconds]
	permission: blackdog.shutdown
	permission message: You do not have permission to shutdown the server.
	trigger:
...
```
from the console
```
> shutdown 5
```
or in-game (by admins with blackdog.shutdown permission)
```
/shutdown 5
```

**Comment by I2000C** [comment]
[NewAmazingLuckyBlocks_custom-outcomes_test3.zip](https://github.com/I2000C/NewAmazingLuckyBlocks/files/3216797/NewAmazingLuckyBlocks_custom-outcomes_test3.zip)
Now, you can change the command's sender:
![Sin título](https://user-images.githubusercontent.com/29607352/58326923-7ea74e80-7e2e-11e9-8805-64570fb4245e.png)
I hope this should work correctly with Skript scripts

**Comment by SlimeDog** [comment]
It does not, in either Spigot 1.13.2 final or 1.14.1 latest. As I explained above, the skripts I cited run both in-game and on the console.

**Comment by I2000C** [comment]
With 
> the skripts I cited run both in-game and on the console

you mean that commands (skripts) can be executed both in game and in console.
However, in order to use them in ALB's outcomes, ALB must know who sends the command (the console / a player)

**Comment by SlimeDog** [comment]
I see. OK. So it works. I think you can release this. :)

custom_outcomes.yml
```
Main-probability: 100
Custom-outcomes:
...
  2:
    outcome-name: "Example 2"
    probability: 100
    rewards:
      item:
        0:
          material: RED_WOOL
          amount: 2 
      command:
        0: 
          cmd: say "hit me!"
          sender: Console
        1:
          cmd: smite-me
          sender: Player
```
Result (in-game)
- 2 red wool
- [playerName] "hit me!"
- lightning strikes caused by smite-me

BTW, "Console" and "Player" do not have to be capitalized (I tested both ways).
